# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

resources:
- repo: self

pool:
    vmImage: "ubuntu-latest"
    
steps:
- task: JenkinsQueueJob@2
  inputs:
    serverEndpoint: 'jenkins'
    jobName: 'streamingapp'
    captureConsole: true
    capturePipeline: true
    isParameterizedJob: false